//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail_BK
    {
        public long Id { get; set; }
        public long TransactionDetailId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<long> UnitPrice { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal TaxRate { get; set; }
        public Nullable<long> TotalAmount { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> IsDeductedBy { get; set; }
        public string BatchNo { get; set; }
        public string BdDiscounted { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
