//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIPMemberRule
    {
        public VIPMemberRule()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string RuleName { get; set; }
        public long Amount { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsCalculatePoints { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
